project:
  type: book
  output-dir: docs
book:
  title: "Stockholmsenkäten"
  subtitle: "Psykometrisk analys med Rasch-metodik"
  repo-url: "https://github.com/pgmj/sthlmsenk"
  sidebar:
    style: floating
    search: true
  author: 
    name: 'Magnus Johansson'
    affiliation: 'RISE Research Institutes of Sweden'
    affiliation-url: 'https://ri.se/shic'
    orcid: '0000-0003-1669-592X'
  date: last-modified
  chapters:
  - index.qmd
  - 01_Intro/01_Intro.qmd
  - 02_IF/02_Individfaktorer.qmd
  - 03_Skola/03_Skola.qmd
  - 04_PSF/04_PSF.qmd
  - 05_Parenting/05_Parenting.qmd
  - 06_KamraterFritid/06_KamraterFritid.qmd
  - 07_Community/07_Community.qmd
  - Wellbeing/WellbeingSthlm.qmd
  - 08_Mobbning/08_Mobbning.qmd
  - 09_ANDTS/09_ANDTS.qmd
  - 10_Brott/10_Brott.qmd
  
format:
  html:
    logo: rise_logo_quarto.png
    mainfont: 'Lato'
    monofont: 'Roboto Mono'
    linestretch: 1.6
    theme: 
      - materia
      - custom.scss
    css: styles.css
    link-external-newwindow: true
    fig-dpi: 96
    license: CC BY
    crossref-sec-prefix: "Sektion"
    toc-title: "Innehållsförteckning"
    crossref-fig-title: "Figur"
    crossref-tbl-title: "Tabell"
    callout-note-title: "Beskrivning"